config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  root 'welcome#index'
  
  get 'introduction', to: "grammar_pages#introduction"
  get 'orthography', to: "grammar_pages#orthography"
  get 'phonology', to: "grammar_pages#phonology"
  get 'sound_changes', to: "grammar_pages#sound_changes"
  get 'personal_pronouns', to: "grammar_pages#personal_pronouns"
  get 'verbal_paradigm', to: "grammar_pages#verbal_paradigm"
  get 'forum', to: "categories#index"
  get 'calendar_view', to: "calendars#show"
  
  resources :categories, only: :show do
    resources :posts do
      resources :comments
    end
  end
  
  resources :users, only: :show do
    resources :bios, only: [:new, :create, :edit, :update]
  end
  
  resources :user_notifications, only: :destroy
  
  get 'responsive/:action', :controller => :responsive
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bio.rb
class Bio < ApplicationRecord
  belongs_to :user, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true, dependent: :destroy
  belongs_to :post, dependent: :destroy
  belongs_to :category, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user, optional: true
  has_many :comments, :dependent => :destroy
  has_many :user_notifications, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_one :bio, :dependent => :destroy
  has_many :user_notifications, :dependent => :destroy
end

app/models/user_notification.rb
class UserNotification < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def new
    @user = User.find(params[:user_id])
    @bio = Bio.new
  end
  
  def create
    @user = User.find(params[:user_id])
    @user.create_bio(bio_params)
    redirect_to user_path(@user)
  end
  
  def edit
    @user = User.find(params[:user_id])
    @bio = Bio.find(params[:id])
  end
  
  def update
    @user = User.find(params[:user_id])
    @bio = Bio.find(params[:id])
    
    if @user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end
    
    @bio.update_attributes(bio_params)
    redirect_to user_path(@user)
  end
  
  private
  
  def bio_params
    params.require(:bio).permit(:bio)
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def generate
    
  end
  
  def show
    @year = params[:year]
    @month = params[:month]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @category = Category.find(params[:category_id])
    @category.posts.create(post_params)
    redirect_to category_path(@category)
  end
  
  def show
    @category = Category.find(params[:category_id])
    @post = @category.posts.find(params[:id])
    @comment = Comment.new
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :content, :user_id, :guest_name, :guest_email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    if @user.bio.present?
      @bio = @user.bio
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grammar_pages_helper.rb
module GrammarPagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/responsive_helper.rb
module ResponsiveHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calendars/show.html.erb
<% if params[:metonic] == "1" %>
	<% metonic = true %>
<% else %>
	<% metonic = false %>
<% end %>

<% year_input = params[:year] %>
<% month_input = params[:month] %>

<div class="spacer"></div>

<div class="calendar-form">
	<div class="calendar-form-wrapper">
		<h3 style="color: #D4AB1D;">Generate Calendar</h3><br />
		
		<%= form_tag(calendar_view_path, method: :get) do %>
			<% if params[:year].present? %>
				<%= text_field_tag(:year, params[:year]) %><br />
			<% else %>
		    	<%= text_field_tag(:year, "Year") %><br />
		    <% end %>
		    <%= label_tag :year, "Year must be in BG (BG = CE + 1019)"%><br /><br />
		    <%= select_tag :month, options_for_select([['Quimonios', 'Quimonios'], ['Samonios', 'Samonios'], ['Dumanios', 'Dumanios'], ['Riuros', 'Riuros'], ['Anagantios', 'Anagantios'], ['Ogronios', 'Ogronios'], ['Cutios', 'Cutios'], ['Rantaranos', 'Rantaranos'], ['Giamonios', 'Giamonios'], ['Simiuisonna', 'Simiuisonna'], ['Equos', 'Equos'], ['Elembi', 'Elembi'], ['Aedrinni', 'Aedrinni'], ['Cantlos', 'Cantlos']], params[:month])%><br /><br />
		    <% if params[:metonic] == "1" %>
		    	<%= check_box_tag :metonic, "1", true %>
		    <% else %>
		    	<%= check_box_tag :metonic %>
		    <% end %>
		    <%= label_tag :metonic, "Metonic?" %><br /><br />
		    <%= submit_tag "Submit" %>
		<% end %>
	</div>
</div>

<% if params[:year].present? && params[:month].present? %>
	<% if !Coligny::ColignyYear.new(params[:year].to_i, metonic).months.find { |s| s.name == params[:month].to_s }.nil? %>
		<div class="calendar-container">
			<div class="calendar-wrapper">
				<div class="calendar-header"><h2><%= params[:month].to_s + " " + params[:year].to_s %></h2></div>
				<br />
				<br />
				<div class="calendar-block">
					<p>Sunday</p>
				</div>
				<div class="calendar-block">
					<p>Monday</p>
				</div>
				<div class="calendar-block">
					<p>Tuesday</p>
				</div>
				<div class="calendar-block">
					<p>Wednesday</p>
				</div>
				<div class="calendar-block">
					<p>Thursday</p>
				</div>
				<div class="calendar-block">
					<p>Friday</p>
				</div>
				<div class="calendar-block">
					<p>Saturday</p>
				</div>
				<% if params[:metonic] == "1" %>
					<% date = Coligny::ColignyYear.new(params[:year].to_i, true) %>
				<% else %>
					<% date = Coligny::ColignyYear.new(params[:year].to_i) %>
				<% end %>
				<% month = date.months.find { |s| s.name == params[:month] } %>
				<% if params[:metonic] == "1" %>
					<% Coligny::ColignyDate.new(params[:year].to_i, params[:month], 1, true).to_gregorian_date.wday.times do |block| %>
						<div class="calendar-block">-</div>
					<% end %>
				<% else %>
					<% Coligny::ColignyDate.new(params[:year].to_i, params[:month], 1).to_gregorian_date.wday.times do |block| %>
						<div class="calendar-block">-</div>
					<% end %>
				<% end %>
				<% (1...(month.days + 1)).each do |day| %>
					<div class="calendar-block">
						<h1><%= day %></h1>
						<% if params[:metonic] == "1" %>
							<h4><%= Coligny::ColignyDate.new(params[:year].to_i, params[:month], day, true).to_gregorian_date %></h4>
						<% else %>
							<h4><%= Coligny::ColignyDate.new(params[:year].to_i, params[:month], day).to_gregorian_date %></h4>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
	<% else %>
		<br />
		<div class="calendar-error-container">
			<div class="calendar-error-wrapper">
				<p class="calendar-error">Month not present in year specified!</p>
			</div>
		</div>
	<% end %>
<% end %>

<div style="clear: both;"></div>
<br />