config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  root 'welcome#index'
  
  get 'introduction', to: "grammar_pages#introduction"
  get 'orthography', to: "grammar_pages#orthography"
  get 'phonology', to: "grammar_pages#phonology"
  get 'sound_changes', to: "grammar_pages#sound_changes"
  get 'personal_pronouns', to: "grammar_pages#personal_pronouns"
  get 'verbal_paradigm', to: "grammar_pages#verbal_paradigm"
  get 'forum', to: "categories#index"
  get 'calendar_view', to: "calendars#show"
  
  resources :categories, only: :show do
    resources :posts do
      resources :comments
    end
  end
  
  resources :users, only: :show do
    resources :bios, only: [:new, :create, :edit, :update]
  end
  
  resources :user_notifications, only: :destroy
  
  get 'responsive/:action', :controller => :responsive
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bio.rb
class Bio < ApplicationRecord
  belongs_to :user, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true, dependent: :destroy
  belongs_to :post, dependent: :destroy
  belongs_to :category, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user, optional: true
  has_many :comments, :dependent => :destroy
  has_many :user_notifications, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_one :bio, :dependent => :destroy
  has_many :user_notifications, :dependent => :destroy
end

app/models/user_notification.rb
class UserNotification < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/bios_controller.rb
class BiosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def new
    @user = User.find(params[:user_id])
    @bio = Bio.new
  end
  
  def create
    @user = User.find(params[:user_id])
    @user.create_bio(bio_params)
    redirect_to user_path(@user)
  end
  
  def edit
    @user = User.find(params[:user_id])
    @bio = Bio.find(params[:id])
  end
  
  def update
    @user = User.find(params[:user_id])
    @bio = Bio.find(params[:id])
    
    if @user != current_user
      return render text: 'Not Allowed', status: :forbidden
    end
    
    @bio.update_attributes(bio_params)
    redirect_to user_path(@user)
  end
  
  private
  
  def bio_params
    params.require(:bio).permit(:bio)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
    @post = Post.new
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(comment_params)
    
    if @post.user != current_user
      notification = UserNotification.create(notification: "A user has commented on your post:", user_id: @post.user.id, post_id: @post.id)
    end
    
    post_commenters = []
    
    @post.comments.each do |comment|
      post_commenters << comment.user
    end
    
    post_commenters = post_commenters.uniq
    
    post_commenters.each do |poster|
      if poster != current_user
        sibling_notification = UserNotification.create(notification: "A user has commented on a post that you are following:", user_id: poster.id, post_id: @post.id)
      end
    end
    
    redirect_to category_post_path(@category, @post)
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:message, :category_id, :post_id, :user_id, :guest_name, :guest_email)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @category = Category.find(params[:category_id])
    @category.posts.create(post_params)
    redirect_to category_path(@category)
  end
  
  def show
    @category = Category.find(params[:category_id])
    @post = @category.posts.find(params[:id])
    @comment = Comment.new
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :content, :user_id, :guest_name, :guest_email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    if @user.bio.present?
      @bio = @user.bio
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bios_helper.rb
module BiosHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grammar_pages_helper.rb
module GrammarPagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/responsive_helper.rb
module ResponsiveHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/index.html.erb
<div class="spacer"></div>

<div class="box box1">
	<div class="inner">
		<br />
		<div class="categories">
			<% @categories.each do |category| %>
				<div class="category-container">
					<h1><%= link_to category.name, category_path(category) %></h1><br />
					<p><%= category.description %></p><br />
				</div>
				<br />
			<% end %>
		</div>
	</div>
</div>

app/views/categories/show.html.erb
<div class="spacer"></div>
<div class="small-spacer"></div>

<div class="header-half-2 col-xs-12 col-sm-7">
	<h1 class="text-center">Posts in the <%= @category.name %> forum.</h1>
</div>
<div class="header-half-2 col-xs-12 col-sm-5">
	<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
	  Add A New Post
	</button>
</div>
<div style="clear: both;"></div>
<div class="small-spacer"></div>
<div class="forum-box box box1">
	<div class="inner">
		<div class="categories">
			<% @category.posts.each do |post| %>
				<div class="category-container">
					<h2><%= link_to post.title, category_post_path(@category, post) %></h2>
					<br/>
					<% if post.user.id == 4 %>
						<p><%= post.guest_name %></p>
						<p>Guest</p>
						<p><%= post.guest_email %></p>
					<% else %>
						<p><%= post.user.name %></p>
						<p><%= post.user.email %></p>
					<% end %>
				</div>
				<br />
			<% end %>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" id="modal-diag-center" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add A New Post</h4>
      </div>
      <%= form_for @post, url: category_posts_path(@category) do |f| %>
      	  <div class="modal-body">
			<% if current_user %>
				<%= f.hidden_field :user_id, :value => current_user.id %>
			<% else %>
				<%= f.hidden_field :user_id, :value => 4 %>
				<div class="field">
					<%= f.label :guest_name %><br />
					<%= f.text_area(:guest_name, size:"24x1") %>
				</div>
				<br />
				<div class="field">
					<%= f.label :guest_email %><br />
					<%= f.email_field(:guest_email, size:"24x1") %>
				</div>
				<br />
			<% end %>
			<div class="field">
				<%= f.label :title %><br />
				<%= f.text_area(:title, size:"24x1") %>
			</div>
			<br />
			<div class="field">
				<%= f.label :content %><br />
				<%= f.text_area(:content, size:"24x6") %>
			</div>
			<br />
      	  </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <%= f.submit "Add a Post", class: 'btn btn-primary' %>
	      </div>
      <% end %>
    </div>
  </div>
</div>